name = "terp-website"
type = "webpack"
route = ''
zone_id = '000fde296cba847a78e918414382ba7a'
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "./build",entry-point = "workers-site"}
compatibility_date = "2022-06-06"

[env.staging]
route = 'https://staging.terp.network/*'

[env.release]
route = 'https://terp.network/*'
